/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as StudentsEditIdRouteImport } from './routes/students.edit.$id'
import { Route as AssessmentsEditIdRouteImport } from './routes/assessments.edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsEditIdRoute = StudentsEditIdRouteImport.update({
  id: '/students/edit/$id',
  path: '/students/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsEditIdRoute = AssessmentsEditIdRouteImport.update({
  id: '/assessments/edit/$id',
  path: '/assessments/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/staff/profile': typeof StaffProfileRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/assessments/edit/$id': typeof AssessmentsEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/staff/profile': typeof StaffProfileRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
  '/users': typeof UsersIndexRoute
  '/assessments/edit/$id': typeof AssessmentsEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/staff/profile': typeof StaffProfileRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/new': typeof StudentsNewRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/assessments/edit/$id': typeof AssessmentsEditIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/signup'
    | '/assessments/new'
    | '/staff/profile'
    | '/students/$id'
    | '/students/new'
    | '/assessments/'
    | '/staff/'
    | '/students/'
    | '/users/'
    | '/assessments/edit/$id'
    | '/students/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/signup'
    | '/assessments/new'
    | '/staff/profile'
    | '/students/$id'
    | '/students/new'
    | '/assessments'
    | '/staff'
    | '/students'
    | '/users'
    | '/assessments/edit/$id'
    | '/students/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/signup'
    | '/assessments/new'
    | '/staff/profile'
    | '/students/$id'
    | '/students/new'
    | '/assessments/'
    | '/staff/'
    | '/students/'
    | '/users/'
    | '/assessments/edit/$id'
    | '/students/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarksRoute: typeof MarksRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsNewRoute: typeof StudentsNewRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  AssessmentsEditIdRoute: typeof AssessmentsEditIdRoute
  StudentsEditIdRoute: typeof StudentsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/edit/$id': {
      id: '/students/edit/$id'
      path: '/students/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof StudentsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/edit/$id': {
      id: '/assessments/edit/$id'
      path: '/assessments/edit/$id'
      fullPath: '/assessments/edit/$id'
      preLoaderRoute: typeof AssessmentsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarksRoute: MarksRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  StaffProfileRoute: StaffProfileRoute,
  StudentsIdRoute: StudentsIdRoute,
  StudentsNewRoute: StudentsNewRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  AssessmentsEditIdRoute: AssessmentsEditIdRoute,
  StudentsEditIdRoute: StudentsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
